import { injectUsMap } from "./usmap/usmap.js";
import { zipcodesInRadius } from "./zipcode/zipcode.js";

import { isJsonSiloInitDone, jsonSiloInit } from "./simulate/jsonsilo.js";
import { isUiInitDone, uiInit } from "./ui.js";
import { setStatusMessage } from "./statusmessage.js";

import { petCardInit, makePetCard } from "./petcard.js";

//===========================================================
// When the DOM is done loading, fill in the zipcode box
//===========================================================

function initSearchForm() {

    // Remove the disabled class from the form
    document.querySelector("#searchFormInputs").classList.remove("searchFormInputsDisabled");

    // Add the enabled class to the form
    document.querySelector("#searchFormInputs").classList.add("searchFormInputsEnabled");

    // setStatusMessage("Ready");
}

let fetchingUsers = false;

// initialize the application. This is called every second checking to make sure everything is done
async function initApp() {

    console.log("Initializing...");

    // Initialize the database engine
    if (!isJsonSiloInitDone()) {

        if (!fetchingUsers) {

            fetchingUsers = true;
            setStatusMessage("Fetching users...");
        }

        try {
            await jsonSiloInit();
        } catch (error) {
            console.error("Error initializing database engine: ", error);
            if (error instanceof Error) {
                console.error("Error name: ", error.name);
                console.error("Error message: ", error.message);
                console.error("Error stack: ", error.stack);
            }
        }
    }

    // Initialize the UI AFTER the database engine
    if (isJsonSiloInitDone() && !isUiInitDone()) {
        try {
            setStatusMessage("Fetching geolocation zip code...");

            await uiInit();
        } catch (error) {
            console.error("Error initializing autocomplete: ", error);
            if (error instanceof Error) {
                console.error("Error name: ", error.name);
                console.error("Error message: ", error.message);
                console.error("Error stack: ", error.stack);
            }
        }
    }

    // If everything is done
    if (isJsonSiloInitDone()
    && isUiInitDone()
    ) {

        console.log("Everything is done, enabling form");

        // Enable the form
        initSearchForm();
    }

    else {

        console.log("Still waiting...");

        // Otherwise, wait a second and try again
        setTimeout(initApp, 1000);
    }
}






// Initialize the map
injectUsMap("mapOfUsa");

// Initialize the petCard library
petCardInit("petCardTemplate");

document.addEventListener("DOMContentLoaded", async function() {


    // Initialize the app
    setTimeout(initApp, 1000);

    }, false);

window.alert("This program meets the sba308a GET requirements through 4 different APIs: " +
            "(get zipcode from IP address (ip-api.com), then get city from zip code " +
            "(zip-api.eu), load database into memory (jsonsilo.com) and load favorites " +
            "(getpantry.cloud).\n\nThis program meets the requierements of doing a POST " +
            "through saving favorites (getpantry.cloud).\n\n" +
            "Click on a state to do a database search.  Click on the hearts to like " +
            "and dislike pets. The application autosaves the favorites every 5 seconds " +
            "on a setTimeout(). The form on the left is not working yet.");

window.alert("Note 1: The JSON database of pets/users was pre-generated by AI " +
            "and is hosted on jsonsilo.com. The dataset contains alot of duplicates!\n\n" +
            "Note 2: The application does take about 5 seconds to do the geolocation "+
            "stuff, and you can see the status under the zip code in the form.  " +
            "Be patient for 5 seconds before you click on a state.\n");

// Zip Codebase Works
// await zipCodebaseTest()
// Free API
// console.log("calling zipcodesInRadius");
// zipcodesInRadius("90012", "5");
// //  zipcodesInRadius("90012", "500");
// console.log(petName);

console.log("Loaded script.js");
